### ISSUE TITLE
Create new account for customer

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#1]
# User Authentication Module
## 1.1 Registration
> Objective: The feature allows users to create an account to access the feature.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>Registration Feature</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Registration<TD>As a new user, I want to create an account so that I can access the platform's features.<TD>

**S1: Registration Form**

* When I navigate to the registration page, I should see a form with the following fields:

1. Full Name (required)

2. Email Address (required, must be unique)

3. Password (required, minimum 6 Characters)

4. Confirm Password (required, must match the entered password)

* The form should include a "Sign Up" button.

**S2: Successful Registration**

* When I fill in all required fields with valid information and click "Sign Up", I should be redirected to the Register Confirmation Page.

* When I click the "Sign in" hyperlink in the Register confirmation page, I should be directed to Login page 

**S3: Invalid Input**

* If I leave any required field empty or enter invalid data (such as an incorrect email format or insufficient password complexity), an error message should be displayed next to the respective field.

* If I enter an email address that is already registered, I should see an error message indicating that the email address is already in use.

* If I enter a password and its confirmation does not match, I should see an error message indicating that the passwords do not match.

<TD>Add comments
    <TR>       
</TABLE>

**Comment by haneeva** [comment]
Added Roles Field for Sign Up Form

**Comment by haneeva** [comment]
Remove the Role Field in Sign Up Form

**Comment by mmafrar** [comment]
@haneeva @M4ash Figma URL for User Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-2&mode=design
