### ISSUE TITLE
Create message in contact page for customer

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#12]
# Contact Management
## 5.1 Create New Message
> Objective: The feature allows customers to create messages on the contact page.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>Create New Message</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Contact Management<TD>As a customer, I want to easily find the contact information so that I can reach out to the company for inquiries or support.<TD>

1. When customers navigate to the Yummy website

2. Then the customer can click the "Contact" menu in the header

3. Customer should be able to see the Contact Page

<TD>Add comments <TR>

<TR>
        <TH>Contact Management<TD>As a potential customer, I want a contact form that is simple and easy to fill out, so I can quickly send a message to the company regarding my questions or concerns.<TD>

1. When customers navigate to the Yummy website

2. Then the customer can click the "Contact" menu in the header

3. Customer should be able to see the Contact Page

4. Form contact should be included:

- Name

- Email

- Subject

- Message

5. When customers click the "send message" button, they will be directed to a message confirmation page.

<TD>Add comments <TR>       
</TABLE>

**Comment by mmafrar** [comment]
Pull request #17 approved and merged to main branch
