### ISSUE TITLE
View and update my profile for customers

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#13]
# User Management
## 6.1 View and Update Profile
> Objective: The feature allows customers to view and update their profiles.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>View and Update Profile</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>User Management<TD>As a customer, I want to easily find my profile page so that I can manage the profiles.<TD>

1. When customers navigate to the Yummy website and login with their valid account

2. Then the customer can click the "My Profile" menu in the header

3. Customer should be able to see the My Profile Page

<TD>Add comments <TR>

<TR>
        <TH>User Management<TD>As a customer, I want to be able to update my profiles so that I can see new my data profiles.<TD>

1. When customers navigate to the Yummy website

2. Then the customer can click the "My profile" menu in the header

3. Customer should be able to see the My profile Page

4. WHen customers click "edit" button
 
5. My profile page should be editable includes:

- Name

- Address

- Email

- Photo Profile

7. When customers click the "save" button, they will see alert notification success updated.

8. If system cannot update the changes, it will be shown an error message. 

<TD>Add comments <TR>       
</TABLE>

**Comment by mmafrar** [comment]
@haneeva @Maimymai Figma URL for User Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-2&mode=design
