### ISSUE TITLE
View about us restaurant for customers

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#14]
# About Us
## 7.1 View About us
> Objective: The feature allows customers to view about restaurant.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>View About us</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>About Us<TD>As a customer, I want to see the details about the restaurant so that I can know their history<TD>

1. When customers navigate to the Yummy website

2. Then the customer can click the "About" menu in the header

3. Customer should be able to see About restaurant

<TD>Add comments <TR>

**Comment by Pravin030399** [comment]
hi @mmafrar , regarding the task. I believe its already there right. Since i could see the information regarding the restaurant

**Comment by mmafrar** [comment]
@Pravin030399 Referring to your comment, assigning this to @Naqibullah-sediqi as he already completed the work

**Comment by mmafrar** [comment]
Assigning @Pravin030399 as he completed unit testing for this
