### ISSUE TITLE
Login account for customer and admin

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#2]
# User Authentication Module
## 1.2 Login
> Objective: The feature allows users to log in to their account and enable them to access the feature.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>Login Feature</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Login<TD>As a User, I want to be able to login into my account so that I can access the features<TD>

**S1: Form Login**

* When I navigate to the login page, I should see a form with the following fields:

1. Email Address (required)

2. Password (required, minimum 6 Characters)

* The form should include a "Sign In" button.

**S2: Login with Valid Credential**

* When I fill in all required fields with valid information and click "Sign In", I should be redirected to the DASHBOARD Page based on ROLES.

**S3: Invalid Input**

* If I leave any required field empty or enter invalid data (such as an incorrect email or password, an error message should be displayed next to the respective field.

<TD>Do we need the maximum login attempt locked?
    <TR> 
<TH>Login<TD>As a User, I want to be able to view my Profile so that I can see my name<TD>

**S1: View My Profile**

* When I navigate to the dashboard page, I should see the My Profiles menu with the following fields:
1. Full Name
2. Email Address

    <TR>

<TH>Login<TD>As a User, I want to be able to log out from my account so that I can ensure the security of my account<TD>

**S1: Logout Account**

* When I click Log out, I should be directed to Login Home Page.
    <TR>
</TABLE>

**Comment by haneeva** [comment]
Added 2 additional user stories regarding My profile and Logout account.

**Comment by mmafrar** [comment]
@haneeva @M4ash Figma URL for User Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-2&mode=design
