### ISSUE TITLE
Create, Read, Update, and Delete food menu for Admin

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#4]
# Menu Management
## 2.1 CRUD Foods
> Objective: The feature allows Admin to create, read, update, and delete food items.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>CRUD Foods Feature</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Menu Management<TD>As an Admin, I want to be able to manage the menu So that I can update, add, or remove items easily to keep it current and appealing to customers.<TD>

1. As an Admin, I should be able to log into the menu management system using my credentials securely.

2. Once logged in, I should see a dashboard or menu management section where I can view the current list of menu items.

3. I should have the option to add a new menu item, providing details such as name, description, price, category, and an optional image.

4. I should be able to edit existing menu items, allowing me to update information such as name, description, price, category, and image.

5. I should have the capability to remove menu items that are no longer available or have been discontinued.

6. When adding or editing items, I should be able to categorize them into sections such as appetizers, main courses, desserts, etc.

7. I should have the capability to view the list of restaurants using the menu items.

8. The menu management system should provide a user-friendly interface that is easy to navigate and use, even for someone without technical expertise.<TR>

<TD>Add comments
    <TR>       
</TABLE>

**Comment by mmafrar** [comment]
@haneeva @Naqibullah-sediqi Figma URL for Menu Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-3&mode=design
