### ISSUE TITLE
Place, track, and manage the order for Customers

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#6]
# Order Management
## 3.1 Manage Order
> Objective: The feature allows customers to place, track, and manage their order.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>Manage Order</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Order Management<TD>As a customer using the Yummy food ordering platform, I want a smooth and intuitive order management system that allows me to place, track, and manage my orders effortlessly.<TD>

1. After logging in to my account,  I can browse through different cuisines, view menu items with detailed descriptions and prices, and easily add items to my cart.

2. When ready to place my order, I proceed to checkout where I review my cart with all selected items.

3. The checkout process is straightforward, with clear prompts for delivery or pickup, address delivery, payment method selection, and order confirmation.

4. After placing my order, I can track the order status updates, showing when it's being prepared, out of delivery, and delivered

5. I have access to my complete order history within my Yummy account.

<TD>Add comments
    <TR>       
</TABLE>

**Comment by mmafrar** [comment]
@haneeva Figma URL for Order Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-3&mode=design
