### ISSUE TITLE
View restaurant details for customers and admin

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#8]
# Restaurant Management
## 4.1 View Restaurant Details
> Objective: The feature allows customers and admin to view restaurant lists and detailed information.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>View Restaurant Details</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Restaurant Management<TD>As a customer, I want to experience a seamless and enjoyable interaction with restaurants listed on the platform, accurate information, and a delightful dining experience.<TD>

1. When I click the restaurant menu, I am presented with a visually appealing list of featured restaurants. Each restaurant card includes a high-quality image and location address.

2. Clicking on a restaurant card takes me to a detailed restaurant page with comprehensive information. I can view the restaurant's menu, opening hours, address, and contact details.

<TD>Add comments <TR>       
</TABLE>

**Comment by mmafrar** [comment]
@haneeva Figma URL for Restaurant Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-3&mode=design
