### ISSUE TITLE
Create, Read, Updated, and Delete branch restaurants for Admin

### ISSUE THREAD

**Issue by haneeva** [mmafrar/yummy#9]
# Restaurant Management
## 4.2 CRUD Branch Restaurants
> Objective: The feature allows admin to create, update, view, and delete branch restaurants.
<TABLE border="1" style="font-size: 10px;">
    <CAPTION><EM>CRUD Branch Restaurants</EM></CAPTION>
    <TR>
        <TH rowspan="1">Requirements
        <TH rowspan="1">User Story
        <TH rowspan="1">Acceptance Criteria
        <TH rowspan="1">Notes
    <TR>
        <TH>Restaurant Management<TD>As an Admin, I want the ability to effortlessly add new branches to my restaurant chain, ensuring accurate representation of locations and seamless integration with the ordering system.<TD>

1. Clicking on "Add New Branch" presents me with a clear and intuitive form to input branch details.

2. The form prompts me to enter essential information for the new branch, such as:

- Branch Name: Unique identifier for the location.
 
- Address: Complete address including street, city, state, and ZIP code.
 
- Contact Information: Phone number and email for the branch
 
- Operating Hours: Opening and closing times for each day of the week.

3. The form allows me to upload images of the new branch, such as storefront photos.

4. When I click an existing branch, I can edit and delete the branches.

<TD>Add comments <TR>       
</TABLE>

**Comment by mmafrar** [comment]
@haneeva Figma URL for Restaurant Management: https://www.figma.com/file/hjM0xWSadExn3CN0nOfqkv/Yummy?type=design&node-id=67-3&mode=design
